name: deploy gh-pages
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and deploy gh-pages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: All things angular
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
        with:
          github_access_token: ${{ secrets.DEPLOY_SECRET }}
          angular_dist_build_folder: dist/coteach
